### ISSUE TITLE
How do I use the rill package with context

### ISSUE THREAD

**Issue by amikai** [destel/rill#19]
Hi, thank you for creating such a great Go package. I have a question.
How do I use the package with context? For example: when encounter first error in `rill.ForEach`, then cancel other task.
Is there any example?

**Comment by destel** [comment]
Hello, thank you very much for the feedback. I appreciate it.

This package does not handle context itself, but it also doesn't stand in way and lets you easily use contexts when you need them.

I reviewed [your code](https://github.com/amikai/go_prac/blob/fd2a75d24c95ab37bd24d1391ffa7663535630c4/rillex/foreach_test.go#L26) and noticed that you're making good use of the package with context. I have one minor suggestion for improvement: you don't need the `if err != nil {cancel()}` part at the end, because you already have `defer cancel()` call


How it works under the hood:
- You have 5 items in-progress (let's assume n=5)
- One item fails
- ForEach immediately returns the error
- Remaining 4 in-progress items keep being processed in the background
- Any other items that may have remained in the input channel will be silently drained in the background

Steps below will occur only if you used context, as you did in your code
- outer function returns
- defer cancel() gets called
- 4 in-progress items that depend on the context will be cancelled

You can also find some useful information, tips and examples on the topic in this readme section:
https://github.com/destel/rill?tab=readme-ov-file#termination-and-resource-leaks

**Comment by amikai** [comment]
Thanks @destel for explanation.
