### ISSUE TITLE
Add the Chinese document

### ISSUE THREAD

**Issue by mixinju** [destel/rill#49]
Hello, Rill is a very good dev tool. I want to add the Chinese document by pull request. Is it Ok?

**Comment by csh0101** [comment]
if rill have bug, I think it's maybe no easy to find.. what do you think it?

**Comment by destel** [comment]
Thank you for your interest! 
However, since the project is still actively evolving and the documentation frequently changes, I'd prefer to hold off on translations for now. It would be hard to keep all version is sync. Once the API and docs become more stable, we can revisit this. I am closing the issue for now.
